.Dd $Mdocdate: July 22 2015 $
.Dt LIBREFORGE 1
.Os
.Sh NAME
.Nm libreforge
.Nd mechanical computer aided drafting and design
.Sh SYNOPSIS
.Nm libreforge
.Op Fl hV
.Op Fl -help
.Op Fl -version
.Sh DESCRIPTION
.Nm
is a computer aided drafting and design (CADD) program.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h, -help
Print a brief help message listing usage and options then exit
.It Fl V, -version
Print a version message containing brief copyright and license information then
exit
.Sh AUTHORS
.Nm
is written and maintained by
.An Michael B. Eichorn Aq Mt libreforge@michaeleichorn.com .
